[package]
name = "rust-digest"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
edition = "2021"

[lib]
name = "digest"
crate-type = ["staticlib"]

[dependencies]
libc =  "0.2"
ring = "0.14"
