[package]
name = "authentication"
version = "0.1.0"
authors = ["Claus Matzinger <claus.matzinger+kb@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1"
serde = "1"
serde_derive = "1"
env_logger = "0.6"
jsonwebtoken = "6"
futures = "0.1"
actix-service = "0.4"
